### ISSUE TITLE
Datho VPN disconnect issue

### ISSUE THREAD

**Issue by scrag** [datho/datho-xbmc-repo#2]
I am running the lates update of RaspBMC.

Installed OpenVPN via apt-get update and apt-get-install openvpn.

Currently using the free servers. initially it was connecting and advising me of the connected IP. Now it is not indicating the connected IP address - just indicating the VPN is connected.

I can check that the VPN is connected via ifconfig.

When I disconnect the VPN it indicates that the VPN is disconnected but when checking ifconfig it remains connected. The only way to disconnect is to sudo reboot or reboot via the reboot option in RaspBMC.

tun0 remains once the VPN disconnects. tun0 should disappear when VPN disconnects.

**Comment by datho** [comment]
This issue was fixed on 0.9.17
